# Generated by Django 3.1.3 on 2023-07-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230716_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='courses',
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
            preserve_default=False,
        ),
    ]
