# Generated by Django 3.1.3 on 2023-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230717_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='courses',
            new_name='course',
        ),
    ]
